import type { ImageSource } from "../types";

export const makePlaceholderSource = (
  country: string,
  clueTags: string[],
  label = "Image needed"
): ImageSource => ({
  sourceType: "generatedPlaceholder",
  attribution: `${label} placeholder generated by GeoMastery Trainer`,
  license: "Generated placeholder; replace with user-owned or openly licensed imagery",
  country,
  clueTags,
  verificationStatus: "starter",
});

export const sourceRegistry: ImageSource[] = [
  {
    sourceType: "wikimedia",
    attribution: "Openly licensed Wikimedia Commons source; verify exact author on source page before publishing.",
    license: "Open license listed on source page",
    sourceUrl: "https://commons.wikimedia.org/wiki/Main_Page",
    country: "Global",
    clueTags: ["commons", "starter-source"],
    verificationStatus: "verify-before-publishing",
  },
  {
    sourceType: "mapillary",
    attribution: "Mapillary image attribution must be displayed when an API image ID is configured.",
    license: "Use only under Mapillary platform terms",
    apiReference: "Mapillary image ID placeholder",
    country: "Global",
    clueTags: ["mapillary", "optional-api"],
    verificationStatus: "starter",
  },
  {
    sourceType: "googleStreetView",
    attribution: "Google Street View Static API imagery requires API compliance and visible attribution.",
    license: "Use only under Google Maps Platform terms",
    apiReference: "Google Street View Static API reference placeholder",
    country: "Global",
    clueTags: ["street-view-api", "optional-api"],
    verificationStatus: "starter",
  },
];
